title: "Dancing☆Starプリキュア"

characters:
  # c.f. https://twitter.com/precure_stage/status/1747272495546187986
  - name:      キュアブレイク(黒瀬舞人)
    birthday:  "1/17"
    cast_name: 小辻庵

  # c.f. https://twitter.com/precure_stage/status/1783873673557885416
  - name:      キュアソウル(月宮爽々奈)
    birthday:  "4/27"
    cast_name: 森田桐矢

  # c.f. https://twitter.com/precure_stage/status/1788584715735154719
  - name:      キュアロック(夏目颯斗)
    birthday:  "5/10"
    cast_name: 滝澤諒

  # c.f. https://x.com/precure_stage/status/1799093962864795917
  - name:      キュアカグラ(天弦晃雅)
    birthday:  "6/8"
    cast_name: 寺坂頼我

  # c.f. https://x.com/precure_stage/status/1822649175240282307
  - name:      キュアトップ(星河楽)
    birthday:  "8/12"
    cast_name: 田村升吾

  # c.f. https://x.com/precure_stage/status/1844392451001417999
  - name:      鈴ノ木蛍
    birthday:  "10/11"
    cast_name: 平松來馬

  # c.f. https://x.com/precure_stage/status/1867947662915350985
  - name:      内海充
    birthday:  "12/15"
    cast_name: TAISEI

  # c.f. https://x.com/precure_stage/status/1873383473731490190
  - name:      室井一帆
    birthday:  "12/30"
    cast_name: 伊藤裕一
