title: "プリキュア"

# https://github.com/sue445/rubicure で定義されていないキャラの誕生日のみ記載する
characters:
  - name:     "はぐたん"
    birthday: "10/21"

  # c.f. http://www.toei-anim.co.jp/tv/precure/character/chara4.php
  - name:     ラビリン
    birthday: "3/3"
  - name:     ペギタン
    birthday: "4/25"
  - name:     ニャトラン
    birthday: "2/22"
  - name:     ラテ
    birthday: "11/1"
