title: "プリキュア"

# https://github.com/sue445/rubicure で定義されていないキャラの誕生日のみ記載する
characters:
  - name:     "はぐたん"
    birthday: "10/21"
    
  # https://twitter.com/pps_as/status/1228209540224581636
  - name:     ニャトラン
    birthday: "2/22"
