title: "プリキュア"

# https://github.com/sue445/rubicure で定義されていないキャラの誕生日のみ記載する
characters:
  # ＨＵＧっと！プリキュア
  - name:     "はぐたん"
    birthday: "10/21"

  # ヒーリングっど♥プリキュア
  # c.f. http://www.toei-anim.co.jp/tv/precure/character/chara4.php
  - name:     ラビリン
    birthday: "3/3"
  - name:     ペギタン
    birthday: "4/25"
  - name:     ニャトラン
    birthday: "2/22"
  - name:     ラテ
    birthday: "11/1"

  # トロピカル～ジュ！プリキュア
  # c.f. https://twitter.com/miso_katsu/status/1450085557258780674
  - name:     くるるん
    birthday: "9/6"

  # デリシャスパーティ♡プリキュア
  # c.f. https://www.toei-anim.co.jp/tv/precure/character/energy1.php
  - name:     コメコメ
    birthday: "8/18"
  - name:     パムパム
    birthday: "4/12"
  - name:     メンメン
    birthday: "11/11"

  # c.f. https://www.toei-anim.co.jp/tv/precure/character/oicina1.php#charaarea
  - name:     品田拓海
    birthday: "11/3"

  # c.f. https://www.toei-anim.co.jp/tv/precure/character/cooking1.php
  - name:     ローズマリー
    birthday: "8/2"

  # Dancing☆Starプリキュア
  # c.f. https://twitter.com/precure_stage/status/1747272495546187986
  - name:     キュアブレイク(黒瀬舞人)
    birthday: "1/17"

  # c.f. https://twitter.com/precure_stage/status/1783873673557885416
  - name:     キュアソウル(月宮爽々奈)
    birthday: "4/27"

  # c.f. https://twitter.com/precure_stage/status/1788584715735154719
  - name:     キュアロック(夏目颯斗)
    birthday: "5/10"

  # c.f. https://x.com/precure_stage/status/1799093962864795917
  - name:     キュアカグラ(天弦晃雅)
    birthday: "6/8"

  # c.f. https://x.com/precure_stage/status/1822649175240282307
  - name:     キュアトップ(星河楽)
    birthday: "8/12"
