title: "プリキュアのサブキャラ"

# https://github.com/sue445/rubicure で定義されていないキャラの誕生日のみ記載する
characters:
  # ＨＵＧっと！プリキュア
  - name:      "はぐたん"
    birthday:  "10/21"
    cast_name: 多田このみ

  # ヒーリングっど♥プリキュア
  # c.f. http://www.toei-anim.co.jp/tv/precure/character/chara4.php
  - name:      ラビリン
    birthday:  "3/3"
    cast_name: 加隈 亜衣
  - name:      ペギタン
    birthday:  "4/25"
    cast_name: 武田 華
  - name:      ニャトラン
    birthday:  "2/22"
    cast_name: 金田 アキ
  - name:      ラテ
    birthday:  "11/1"
    cast_name: 白石 晴香

  # トロピカル～ジュ！プリキュア
  # c.f. https://twitter.com/miso_katsu/status/1450085557258780674
  - name:      くるるん
    birthday:  "9/6"
    cast_name: 田中あいみ

  # デリシャスパーティ♡プリキュア
  # c.f. https://www.toei-anim.co.jp/tv/precure/character/energy1.php
  - name:      コメコメ
    birthday:  "8/18"
    cast_name: 高森奈津美
  - name:      パムパム
    birthday:  "4/12"
    cast_name: 日岡なつみ
  - name:      メンメン
    birthday:  "11/11"
    cast_name: 半場友恵

  # c.f. https://www.toei-anim.co.jp/tv/precure/character/oicina1.php#charaarea
  - name:      品田拓海
    birthday:  "11/3"
    cast_name: 内田雄馬

  # c.f. https://www.toei-anim.co.jp/tv/precure/character/cooking1.php
  - name:      ローズマリー
    birthday:  "8/2"
    cast_name: 前野智昭

  # わんだふるぷりきゅあ！
  - name:      兎山悟
    birthday:  "9/7"
    cast_name: 寺島拓篤

  - name:      兎山大福
    birthday:  "3/27"
    cast_name: 中村悠一

  - name:        ナツキ
    birthday:    "7/15"
    cast_name:   花澤香菜
    description: "ファミコンが発売された日"
